name: UHCScatter
main: com.publicuhc.uhcscatter.UhcScatterPlugin
version: 1.0.0
description: Scatter addon plugin for UHC
author: ghowden/Eluinhost
website: wiki.publicuhc.com
database: false
depend: [UltraHardcore]
commands:
    sct:
      description: Scatter players
      usage: /<command>
      aliases: [uhcsct]
permissions:
    UHC.scatter.command:
        description: Use the scatter command
        default: op